[package]
name = "chess"
version = "0.1.0"
edition = "2021"

[lib]
name = "chess_logic_lib"
path = "src/lib.rs"

[dependencies]
tungstenite = "0.21.0"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
env_logger = "0.11.3"
log = "0.4.21"
